main: su.nightexpress.gamepoints.GamePoints
version: 1.2.2
name: GamePoints
author: NightExpress
desciption: Additional virtual currency with internal GUI shop.
depend: [ NexEngine ]
softdepend: [ PlaceholderAPI ]
api-version: 1.15
permissions:
#--------------------------------------------------------#
  gamepoints.admin:
    description: Full plugin access.
    default: op
    children:
      gamepoints.cmd: true
      gamepoints.store: true
#--------------------------------------------------------#
  gamepoints.cmd:
    description: Access to all plugin commands.
    default: op
    children:
      gamepoints.cmd.add: true
      gamepoints.cmd.pay: true
      gamepoints.cmd.balance: true
      gamepoints.cmd.balance.others: true
      gamepoints.cmd.balancetop: true
      gamepoints.cmd.removepurchase: true
      gamepoints.cmd.set: true
      gamepoints.cmd.store: true
      gamepoints.cmd.take: true
  gamepoints.cmd.add:
    description: Allows to use 'add' command.
    default: op
  gamepoints.cmd.balance:
    description: Allows to use 'balance' command.
    default: true
    children:
      gamepoints.cmd.balance.others: false
  gamepoints.cmd.balance.others:
    description: Allows to use 'balance' command on other players.
    default: op
  gamepoints.cmd.balancetop:
    description: Allows to use 'balancetop' command.
    default: true
  gamepoints.cmd.pay:
    description: Allows to use 'pay' command.
    default: op
  gamepoints.cmd.removepurchase:
    description: Allows to use 'removepurchase' command.
    default: op
  gamepoints.cmd.set:
    description: Allows to use 'set' command.
    default: op
  gamepoints.cmd.store:
    description: Allows to use 'store' command.
    default: true
  gamepoints.cmd.take:
    description: Allows to use 'take' command.
    default: op
#--------------------------------------------------------#
  gamepoints.store:
    description: Grants access to all stores.
    default: op
#--------------------------------------------------------#